spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: ${dev.datasource.driver-class-name}
    url: jdbc:mysql://${dev.datasource.host}:${dev.datasource.port}/${dev.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${dev.datasource.username}
    password: ${dev.datasource.password}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
